[package]
name = "purrislav"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
poise = "0.6.1"
dotenv = "0.15.0"
regex = "1.11.1"
chrono = "0.4.40"
native_db = "0.8.1"
native_model = "0.4.20"
once_cell = "1.20.3"
serde = { version = "1.0.218", features = ["derive"] }