[package]
name = "purrislav"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.12.4"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
poise = "0.6.1"
dotenv = "0.15.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
regex = "1.11.1"